
## Getting and Cleaning Data - Final project

### Variables:

x_test_train: the final tidy dataset before extracting the variables related with the mean and std.
mean_std: the dataset of the point 5.
x_test, x_train: the main original tables
y_test, y_train: tables with the total activities by activities ID
features, activity, and subjects tables, as indicated in their names.

### Processes

Instead merge the test and training data in the first place, I worked first in each dataset separately, and finally, merged the two datasets.

1) First, I changed the columns names using the features table.
2) I combined (cbind) measurments, subjects and activities in both test and train
3) I did a left join of the function merge to add the activities names
4) I combined test and train through rbind
5) Extraction of the columns related with the mean and std
6) Calculated the point five of the requirements.

In total I added three columns to the original dataset. I run the same process for both, train and test datasets.
Finally, I merged two datasets.

In order to fulfill the requirements of the project, I extracted the variables than I needed to calculate the las question.
So, I extracted the variables related with the mean, std, activities, and subjects. After that, grouped the dataset and aplied
the mean inside a summarize_at function.










