## Getting and Cleaning Data - Final project

### Explanation of the process

I separate the script in six parts:

- In the first part of the script, I loaded all the data sets I needed into R.
- In the second and third part, I worked with the main train and test data sets adding the variables titles, and the necessary columns to work with.
- In the fourth part I created the tidy data sets by merging test and train tidy data sets. I used a merge left join to do so.
- In the fifth part, I extracted the variables related with means, std, activities and subjects, in order to complete the point 5 task.
- Last but not least, I group by and calculated the mean of the variables in the data set.

I chose to merge the train and test data sets when both data sets were completed, with their correspondent variables names and additional columns, instead merge it at the beginning.

In total I added three columns to the original data set. I run the same process for both, train and test data sets.
Finally, I merged two data sets.











